name: Clear Branch History

on:
  workflow_dispatch:

jobs:
  clear:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clear commits
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout --orphan temp_branch
          git add -A
          git commit -m "Initial commit"
          git branch -D $GITHUB_REF_NAME
          git branch -m $GITHUB_REF_NAME
          git push -f origin $GITHUB_REF_NAME
